name: Harmony Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/**.nix"
      - "flake.lock"
  pull_request:
    branches: 
      - master
    paths-ignore:
      - "**/**.nix"
      - "flake.lock"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - 
        name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - 
        name: Get project libraries
        run: go get -v -t -d ./...
      - 
        name: Build
        run: go build -v .
      - 
        name: Test
        run: $HOME/go/bin/go-acc ./...
        continue-on-error: true
      - 
        uses: actions/upload-artifact@v2
        with:
          name: inviter
          path: inviter
      - name: Upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage inviter
